config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create]
  resources :posts, only: [:new, :create, :show, :index, :edit, :update] do
    resources :recipes, only: [:create]
  end

  get '/auth/facebook/callback' => 'sessions#create'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'

  delete 'session' => 'sessions#destroy', as: 'logout'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    belongs_to :post
    belongs_to :user  
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :posts

    def admin_update
        if self.admin == 0
            self.admin = false 
        elsif self.admin == 1
            self.admin = true
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def current_user
      User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
      !!current_user
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user = current_user
        @post.save
        redirect_to current_user
    end
    
    def show
        @post = Post.find_by(id: params[:id])
        @user = current_user
    end

    def index
        @user = current_user
        @posts = Post.all
    end

    def edit
        @post = Post.find_by(id: params[:id])
    end

    def update
        @post = Post.find_by(id: params[:id])
        @post.update(post_params)

        redirect_to @post
    end

    private
    def post_params
        params.require(:post).permit(:title, :ingredients, :directions, :cooktime, :chef, :caption)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def create
        post = Post.find_by(id: params[:post_id])
        @recipe = post.recipes.build(user: current_user)
        @recipe.save
        session[:message] = @recipe.take_recipe
        redirect_to current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create

    @user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.name = auth['info']['name']
      u.email = auth['info']['email']
      u.image = auth['info']['image']
    end
    
    session[:user_id] = @user.id
    render 'welcome/home'

    # if !@user.save
      
    #   @user = User.new(login_params)
    #   session[:user_id] = @user.id
    #   redirect_to @user
    # end
    
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end
  
  private
  
  def auth
    request.env['omniauth.auth']
  end

  def login_params
    params.require(:user).permit(:name, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.admin_update
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else 
      render 'new'
    end
  end

  def show
    redirect_to root_path unless session.include? :user_id
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :admin)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnackOverload2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <!--<link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--<script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8="
      crossorigin="anonymous">
    </script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <script src="/js/bootstrap.min.js"></script>-->
  </head>
  <!--
  <nav class="navbar text-center" style="margin-top: 75px">
    <%= link_to image_tag('logo.svg'), root_path, class: "img-fluid" %>
  </nav>
  -->

  <% if session[:user_id] %>
    <div class="navbar navbar-light bg-light" role="navigation">
      <div class="container" style="margin-top:3rem">
        <div class="row">
          <div class="col-sm-5"></div>
          <div class="col-sm-5"></div>
          <div class="col-sm-2 form-inline navbar-brand">
            <a><img src="<%= @user.image %>"></a>
            <a><%= @user.name %></a>
          </div>
        </div>
      </div>
    </div>

  <% else %>
    <div class="navbar navbar-light bg-light" role="navigation">
      <div class="container" style="margin-top:3rem">
        <div class="row">
          <div class="col-sm-4">
          </div>
          <div class="col-sm-4"></div>
          <div class="col-sm-4">
            <a class="navbar-brand" >Snack Overload <strong>PREMIUM</strong></a>
            <a href="<%= login_url %>" class="btn btn-primary">Login</a>
          </div>
        </div>
      </div>
    </div>
  <% end %>
    

  <body>
    <div class="container">
      <div class="text-center" style="padding-top: 7em">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_for_admins.html.erb
<h1>posts</h1>
<% @posts.each do |post| %>
    <p><%= link_to("Show #{post.name}", post_path(post)) %><p>
<% end %>
<p><%= link_to("New post", new_post_path) %>

app/views/posts/_for_users.html.erb
<h1>Recipes</h1>
<p><%= link_to("New post", new_post_path) %>
<% @posts.each do |post| %>
    <p><%= link_to("#{post.title}", post_path(post)) %><p>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |post_builder| %>
    <p>
        <%= post_builder.label :title %>
        <%= post_builder.text_field :title %>
    </p>

    <p>
        <%= post_builder.label :ingredients %>
        <%= post_builder.text_field :ingredients %>
    </p>

    <p>
        <%= post_builder.label :directions %>
        <%= post_builder.text_field :directions %>
    </p>

    <p>
        <%= post_builder.label :cooktime %>
        <%= post_builder.text_field :cooktime %>
    </p>

    <p>
        <%= post_builder.label :chef %>
        <%= post_builder.text_field :chef %>
    </p>

    <p>
        <%= post_builder.label :caption %>
        <%= post_builder.text_field :caption %>
    </p>

    <%= post_builder.submit %>
<% end %>

app/views/posts/index.html.erb
<% if @user.admin %>
    <%= render 'for_admins' %>
<% else %>
    <%= render 'for_users' %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<strong>Title:</strong> <%= @post.title %><br>
<strong>Ingredients:</strong> <%= @post.ingredients %><br>
<strong>Directions:</strong> <%= @post.directions %><br>
<strong>Cook Time:</strong> <%= @post.cooktime %><br>
<strong>Chef:</strong> <%= @post.chef %><br>
<strong>Caption:</strong> <%= @post.caption %><br>


<%= link_to "Edit Post", edit_post_path(@post) %>

app/views/users/_show.html.erb
<!--<p><%= session[:message] if session[:message] %></p>-->


<!-- show user's recepies -->
<div class="card-group">
  <div class="card">
    
  </div>
  <div class="card">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  <div class="card">
    
  </div>
</div>



<p><%= link_to("See Recipes", posts_path) %>
<p><%= link_to("Log Out", logout_path, method: 'delete') %></p>

app/views/users/new.html.erb
<%= form_for(@user) do |new_user| %>
    <p>
        <label>Name</label>
        <%= new_user.text_field :name %>
    </p>

    <p>
        <label>Email</label>
        <%= new_user.text_field :email %>
    </p>

    <p>
        <label>Check box if you are an admin</label>
        <input class="form-check-input" type="checkbox" value="1" name="user[admin]" id="user_admin">
    </p>

    <p>
        <label>Password</label>
        <%= new_user.text_field :password %>
    </p>

    <%= new_user.submit %>
<% end %>

app/views/users/show.html.erb
<%= render 'show' %>

app/views/welcome/home.html.erb
<% if session[:user_id] %>
    <%= render 'users/show' %>
<% else %>
  <div>
    <%= link_to(image_tag('Continue_with_FB.svg'), '/auth/facebook') %>
  </div>
  <div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4" style="margin-top:3rem">
      <div>
        <h3> <a href="<%= signup_url %>">Or Create Account With Email</a></h3>
      </div>
    </div>
    <div class="col-sm-4"></div>
  </div>
<% end %>